server:
  port: 

spring:
  datasource:
    username: 
    password:
    url: 

  jpa:
    properties:
      hibernate:
        dialect: searchengine.config.MySQL8Dialectutf8mb4

    hibernate:
      ddl-auto: create
    show-sql: false


indexing-settings:
  sites:
    
      
