server:
  port: 8080

spring:
  datasource:
    username: root
    password: Novosib2015
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  
  jpa:
    properties:
      hibernate:
        dialect: searchengine.config.DialectUTF8mb4
    hibernate:
      ddl-auto: create
    show-sql: false

indexing-settings:
  sites:
    - url: http://radiomv.ru/
      name: RadioMV
    - url: http://skillbox.ru/
      name: Skillbox
    - url: http://www.playback.ru/
      name: playback
    - url: https://volochek.life/
      name: volchek
    - url: https://ipfran.ru/
      name: ipfran
    - url: https://dimonvideo.ru/
      name: dimonvideo
    - url: https://nikoartgallery.com/
      name: nikoartgallery

connection-settings:
  refers:
    - value: http://www.vk.ru
    - value: http://www.yahoo.com
  users:
    - value: SearchBot
    - value: Mozilla


