server:
  port: 8080

spring:
  datasource:
    username:
    password:
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true

  jpa:
    properties:
      hibernate:
        dialect: searchengine.config.pojo.MySQL8DIALECTutf8mb4

    hibernate:
      ddl-auto: create
    show-sql: false

indexing-settings:
  sites:


connection-settings:
  refers:
    - value: http://www.vk.ru
    - value: http://www.yahoo.com
  users:
    - value: SearchBot
    - value: Mozilla
